Repository merry-berry-acai/docs, pull requests merged in 2025-02, with the labels that each got.

#29 add app architecture diagram
  README.md
  docs/diagrams/application_architecture_diagram.png
Labels: documentation, aad

#31 Feat/dataflow diagram
  README.md
  docs/diagrams/dataflow_diagram.png
Labels: documentation, dfd

#30 Add kanban screenshots and enhance README section
  README.md
  docs/kanban/kanban_board_early_stage.png
  docs/kanban/kanban_board_issues_list_hd_labels.png
  docs/kanban/kanban_board_mid_stage.png
  docs/kanban/kanban_board_overview.png
  docs/kanban/kanban_example_issue.png
Labels: documentation, kanban
